### ISSUE TITLE
probleme chargement des observations

### ISSUE THREAD

**Issue by brunetfred** [Artelia/Mascaret#10]
Bonjour, 

je n'arrive pas à charger les données des observations (dans paramètres, onglet configuration  )
j'ai la version 0.1.10 du plugin
le message d'erreur est : 
ProgrammingError("ERREUR:  la colonne \xc2\xab comment \xc2\xbb de la relation \xc2\xab observations \xc2\xbb n'existe pas\nLINE 1: INSERT INTO huisne.observations(code,comment,date,type,valeu...\n                                             ^\n",)
Import is done.

Aucune valeur n'est importée. 
ci joint le fichier d'observations à importer, qui au bon format avec 3 lignes d'entêtes et des ; comme séparateurs. 

cordialement, 
Frédéric BRUNET

[sacha_Q_Huisne.txt](https://github.com/Artelia/Mascaret/files/2691196/sacha_Q_Huisne.txt)

**Comment by daoum** [comment]
Bonjour,
Il vous manque une colonne dans la table observation. 
Avez-vous créé le modèle avec cette même version du Plugin ? 
Ou modifiez-vous un modèle plus ancien avec cette version du plugin ? 
Car si c'est le cas, cela pourrait expliquer qu'il vous manque  une colonne.

Cordialement,

Mehdi Pierre DAOU

**Comment by brunetfred** [comment]
Bonjour,

j'ai crée le modèle avec une version antérieure du plugin.
quelle est la solution , dois je revenir à l'ancienne version du plugin ?

Cordialement,

*Frédéric BRUNET *
*Chargé d'études géophysique et modélisation hydraulique
Département Laboratoire de Saint-Brieuc / Risques Naturels et Littoraux *
*Tél.: +33(0)2 96 75 93 30 - Port : +33(0)6 63 34 73 08 - FAX : +33(0)2 
96 75 93 10 *


Centre d’études et d’expertise sur les risques, l’environnement, la 
mobilité et l’aménagement www.cerema.fr <http://www.cerema.fr>
Direction territoriale Ouest / DLSB : 5 rue Jules Vallès - 22015 
Saint-Brieuc cedex
Siège social : Cité des Mobilités - 25, avenue François Mitterrand - CS 
92 803 - F-69674 Bron Cedex - Tél : +33 (0)4 72 14 30 30

**Comment by daoum** [comment]
Bonjour,
Le plus simple actuellement est d'ajouter dans la table de donnée de votre ancien modèle à travers pg_admin, la colonne "comment"  avec comme type  "character varying (50)" à la table "observations".
Pour les futures versions, nous ferons  plus attention à cette problématique.

Cordialement,

Mehdi Pierre DAOU
