### ISSUE TITLE
Erreur à l'import d'un modèle créé sous une ancienne version du plugin

### ISSUE THREAD

**Issue by alexisber** [Artelia/Mascaret#17]
Bonjour,
Je suis en train d'essayer la nouvelle version du plugin (0.3.2) et je rencontre une erreur à l'import d'un modèle préalablement créé sous le plugin (0.1.13).

---------------------------------------------------------------
Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'MascPlugDialog' object has no attribute 'SCHEMA' 
Traceback (most recent call last):
  File "C:/Users/alexis.bernard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\MascPlugDialog.py", line 620, in import_model
    self.add_info(" Shema est {}".format(self.SCHEMA))
AttributeError: 'MascPlugDialog' object has no attribute 'SCHEMA'

**Comment by daoum** [comment]
Bonjour,
Commentez simplement la ligne (avec # devant ) pour que cela fonctionne à la prochaine version, cela sera corrigé

**Comment by alexisber** [comment]
OK, en faisant ça, je parviens à charger un modèle... mais je suis emmené vers une autre erreur : 

File "C:/Users/alexis.bernard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\GraphProfilDialog.py", line 161, in canvasReleaseEvent
              graph_hyd_pk = GraphHydro(feature, self.mgis, {}, '', 'pk')
File "C:/Users/alexis.bernard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\GraphProfilDialog.py", line 1712, in __init__
              self.init_ui()
File "C:/Users/alexis.bernard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\GraphProfilDialog.py", line 1772, in init_ui
              self.run = sorted(self.listeRuns.keys())[-1]
             TypeError: '

**Comment by daoum** [comment]
Après avoir importé votre ancien modèle avez vous bien mis à jours vos tables.

![image](https://user-images.githubusercontent.com/6881363/55962964-319e5d00-5c72-11e9-8511-9b9c4feca5b6.png)

**Comment by alexisber** [comment]
Oui, ça été fait

**Comment by daoum** [comment]
Essayez-vous de visualiser d'ancien résultats ou des nouveaux ? Avec les anciens résultats, il peut peut-être avoir quelques soucis lors de modèle avec des événements (mais avec les cas qui ont été testé, je n'ai pas pu reproduire l’erreur)
Sinon, il y a peut être un problème avec votre table runs dans votre modèle.
Enfin avez vous essayé sur un modèle qui a été créé avec cette nouvelle version ? Reproduisez-vous également cette erreur ?
