### ISSUE TITLE
export csv "hydro. results"

### ISSUE THREAD

**Issue by elepape** [Artelia/Mascaret#18]
The export button csv "hydro. results" does not work.
In version 0.1.13 of the plugin we could work around this problem by selecting the columns of the table Ctrl+C Ctrl+V, but it does not work any more in version 0.3.3 (python error attached).

**Comment by daoum** [comment]
I fixed the problem  of Ctrl+C Ctrl+V for the next update.

On the other hand, the csv export works well for me (I tested version Qgis 2.18 and Qgis 3).
What error is returned to you?  which Qgis version do you use?

**Comment by elepape** [comment]
Hello,
Thank you for fixing the problem.
I am using both Qgis 2.18 (with plugin 0.1.13) and 3.4 (with plugin 0.3.3).
In Qgis 2.18 (plugin 0.1.13) the export creates an empty file but doesn't return any errors.
In Qgis 3.4 (plugin 0.3.3) the export also creates an empty file and returns the following Python error: cf. python_error1.png
And when I try to copy and paste one or several columns in Qgis3.4 (plugin 0.3.3), I get this Python error: cf. python_error2.png
 Best regards,

**Comment by daoum** [comment]
Fixed  in the last version
