### ISSUE TITLE
Limitation de la précision des apports

### ISSUE THREAD

**Issue by alexisber** [Artelia/Mascaret#19]
Bonjour,

En essayant d'appliquer des apports linéaires pour prendre en compte l'apport hydrologique de BV intermédiaires non jaugés, je me suis heurté à des limitations du plugin en terme de précisions.

Dans les lois, le débit est limité à 3 chiffres après la virgule (ce qui signifie le litre/sec quand on parle de débit). Néanmoins, quand on utilise l'apport intermédiaire sur des linéaires très importants, on a besoin d'aller plus bas en précision. 

Est-il possible pour la prochaine sortie de modifier :
creer_Loi
                chaine = ' {time:.3f} {flowrate:.3f}\n' 
à remplacer par
                chaine = ' {time:.3f} {flowrate:.6f}\n'

et Obs_to_Loi
                        chaine = '  {0:4.3f}   {1:3.3f}\n'
à remplacer par
                        chaine = '  {0:4.3f}   {1:3.6f}\n'

D'avance merci,
Cordialement,

**Comment by daoum** [comment]
La précision a été augmenté  : 
- pour creer_Loi : dans la version 1.0.1
- pour Obs_to_Loi :  dans la prochaine version 1.0.2

**Comment by alexisber** [comment]
OK merci. ticket fermé.
