### ISSUE TITLE
Impossible de supprimer des points de mes profils

### ISSUE THREAD

**Issue by alexisber** [Artelia/Mascaret#21]
Bonjour, 

Sans en comprendre la raison, il m'est impossible de supprimer des points de mes profils. La sélection fonctionne depuis le profil (bouton "point selection") et depuis la table mais impossible de supprimer les points sélectionnés.

Alexis

**Comment by daoum** [comment]
L'erreur a été corrigé dans la dernière version 1.0.1 .
