### ISSUE TITLE
Style de la couche "weir"

### ISSUE THREAD

**Issue by alexisber** [Artelia/Mascaret#24]
Tous les seuils s'affichent actuellement comme inactifs : 

Dans le style de la branche, peut-on avoir : 
CASE WHEN  "active" = 'true'  THEN type ELSE 0 END

à la place de
CASE WHEN  "active" = 't'  THEN type ELSE 0 END

**Comment by daoum** [comment]
Ce bug sera corrigé dans le prochain update la version 1.0.2.

**Comment by alexisber** [comment]
OK merci. ticket fermé. Merci de profiter de ce travail sur les styles pour modifier l'ordre d'ouverture par défaut.
