### ISSUE TITLE
Erreur lors de lancement d'un modèle

### ISSUE THREAD

**Issue by elderdrag** [Artelia/Mascaret#28]
Bonjour.

Sur QGis 3.12, j'utilise le plugin Mascaret 3.0.0
J'ai construit un modèle et j'ai remplis la tables 'laws'. Lors de lancement du modèle j'ai des erreurs qui s'affichent. vous les trouverez ci dessous. Je demande si vous avez des idées sur leurs raisons et c'est quoi la solution : 
"
Downloading executable file in "bin" directory
Download ...
Error of request : https://raw.githubusercontent.com/Artelia/Exe_Mascaret/master/bin/mascaret.exe
request timed-out
Error of request : https://raw.githubusercontent.com/Artelia/Exe_Mascaret/master/bin/mascaret_linux
request timed-out
Downloading Done
Creation the geometry is done
UndefinedTable('relation "testcanche.struct_config" does not exist\nLINE 1: SELECT * FROM testcanche.struct_config  WHERE active   ORDER...\n                      ^\n') "

"
TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "C:/Users/youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\MascPlugDialog.py", line 533, in fct_run
    clam.mascaret(self.Klist[self.listeState.index(case)], run)
  File "C:/Users/youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\ClassMascaret.py", line 1375, in mascaret
    dict_lois, dico_loi_struct = self.creer_xcas(noyau)
  File "C:/Users/youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\ClassMascaret.py", line 425, in creer_xcas
    dico_str = self.mdb.select('struct_config', "active", "abscissa")
  File "C:/Users/youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\db\ClassMasDatabase.py", line 828, in select
    cols = [col[0] for col in namCol]
TypeError: 'NoneType' object is not iterable "

**Comment by ccoulet** [comment]
A priori il y a une erreur dans le téléchargement des exécutables (Windows et Linux) de Mascaret.
L'installation des prérequis et du plugin n'a pas posé de problèmes?

**Comment by elderdrag** [comment]
Bonjour,
Merci pour votre réponse.
J'ai réinstaller le plugin avec la version 2.0.0 je n'ai plus l'erreur des exécutables de Mascaret. 
Pour la table struct_config, je l'ai créé manuellement dans la base de données. Sinon, une autre erreur s'affiche et le fichier .xcas ne se crée pas.
TypeError: ' 
Traceback (most recent call last):
  File "C:/Users/youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\MascPlugDialog.py", line 525, in fct_run
    clam.mascaret(self.Klist[self.listeState.index(case)], run)
  File "C:/Users/youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\ClassMascaret.py", line 1317, in mascaret
    dict_lois = self.creer_xcas(noyau)
  File "C:/Users/youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\ClassMascaret.py", line 433, in creer_xcas
    branches["abscdebut"].append(min(temp))
TypeError: '

**Comment by daoum** [comment]
Bonjour,

Pour information dans la version 2.0.0, la table  struct_config ne devrait pas être utilisée.
**Si une erreur due à la table struct_config s’est produite avec la version 2.0.0,  pouvez-vous la poster ?**

Il faut noter que si vous voulez lancer un cas avec une description géométrique des structures, il faut obligatoirement utiliser la version 3.

Pour les erreurs que vous rencontrez, j'aurais quelques questions : 
     **Est-ce que le modèle, que vous utilisez, a été créé avec une ancienne version du plugin puis mise à jour?
     Est-ce que lors de la création d'un modèle avec la version 3.0.0, il y a eu à création de la table struct_config? Si non quelle était l'erreur ?**


Enfin l'erreur où le code plante semble venir d'un problème d'une valeur des abscisses des profils ou de la cohérence la branche associée.
**y  a-t-il un problème avec les abscisses des profils (valeur NULL, non numérique) ?**
**ou  si non cela vient des numéros de la branche associé aux profils (colonne branchnum)  qui est NULL, ou non cohérente ?**

Si le problème vient d'abscisses NULL, il est possible de les mettre à jours  avec le code SQL suivant:

CREATE TRIGGER profiles_calcul_abscisse
    BEFORE INSERT OR UPDATE 
    ON $SCHEMA$.profiles
    FOR EACH ROW
    EXECUTE PROCEDURE public.calcul_abscisse_point();
 
Où $SCHEMA$ est le nom du schéma de la table. La mise à jour s’effectuera lors d’une modification de la table dans qgis. Si une valeur d’abscisse, que vous avez modifiée manuellement, ne s’actualise pas alors repassez  la valeur à NULL, et cela devrait marcher.

**Comment by elderdrag** [comment]
Bonjour, je vous remercie pour cette réponse.

Oui, le modèle a été créé dans la version 2.0.0 et puis mis à jour sur la version 3.0.0. C'est avec cette version que j'ai rencontré l'erreur de la table struct_config. 
Pour les abscisses des profils, il y a une seule branche mais avec différentes zones qui ont des Ks différents et effectivement j'ai trouvé un profil avec valeur NULL. Je vais essayer de mettre les abscisses à jours et je vous tiens au courant si le problème est résolu.
