### ISSUE TITLE
Acknowledge the copyright holder of the copied code

### ISSUE THREAD

**Issue by saberraz** [Artelia/Mascaret#3]
Parts of codes and even icons are identical to RiverGIS plugin:
https://github.com/erpas/rgis

I suggest, either to have it as an extension to RiverGIS so that we can have one pre-processing tool for various models.  Or at least acknowledge where you are copying the code from.

**Comment by ccoulet** [comment]
We will acknowledge RiverGis developer in our plugin.
Merging both will be to complicated as the models are really different but if you would like to try, feel free.
