### ISSUE TITLE
erreur création modèle (manque des couches)

### ISSUE THREAD

**Issue by brunetfred** [Artelia/Mascaret#33]
Bonjour, 
lors de la création d'un nouveau modèle, il y a une erreur sur la création des couches  "branch" et "basin". 
Ces couches ne sont pas créées automatiquement. 
je travaille avec la version 3.0.7 et QGIS 3.10.6-A Coruña

**Comment by brunetfred** [comment]
oui,  javais joint une image avec le code de l'erreur (mais il n'apparait pas...)
voici le message : 
Running Create Layers and Tables...

Model "loir_version_vendome" created.
UndefinedFunction("ERREUR:  la fonction chstate_branch() n'existe pas\n")
Process aborted!
UndefinedFunction("ERREUR:  la fonction chstate_basin() n'existe pas\n")
Process aborted!
Model "loir_version_vendome" completed

**Comment by daoum** [comment]
Cela vient comme indiqué de fonction qui ne sont pas créer.  
Il faudrait tester la prochaine version (d'ici la fin de semaine) car il y a eu quelques modifications dans l'ordre de création des fonctions lors de la création d'un modèle. Cela réglera sûrement le problème si ce n'est pas le cas, n'hésitez pas à me tenir au courant.

Si vous voulez pas attendre, la version de la branche master de github a été mise à jours.

Cordialement,

**Comment by brunetfred** [comment]
ok 
merci et bonne journée

**Comment by ccoulet** [comment]
La nouvelle version stable 3.1.0 a été déposée et devrait être approuvée dans la journée. Elle sera donc visible pour les utilisateurs dans la foulée.
