### ISSUE TITLE
Error messages when uppercase letters are used in model name

### ISSUE THREAD

**Issue by pBagot** [Artelia/Mascaret#4]
Hello,
I have encountered 3 error messages:
1 - creation of a new model: 
Model "Test_mascaret" created.
ProgrammingError('ERREUR:  erreur de syntaxe sur ou pr\xc3\xa8s de \xc2\xab ) \xc2\xbb\nLINE 1: INSERT INTO Test_mascaret.parametres() VALUES );\n                                             ^\n',)
Model "Test_mascaret" completed
2 - click on Run/parameters/event:
KeyError: 'evenement'
3 - click on Run:
KeyError: 'repriseCalcul'

I first believed that there was some problems with the versions of postgres/postgis but after testing, it appears that these errors are generated only when uppercase letters are used in the model name.

Yours,
Philippe Bagot

**Comment by daoum** [comment]
In the latest version, these errors are fixed
