### ISSUE TITLE
Demande d'évolution de Mascaret - charge maximale (paramètres résultats)

### ISSUE THREAD

**Issue by elepape** [Artelia/Mascaret#6]
Ajouter comme paramètres résultats à Mascaret la charge maximale pour pouvoir la comparer à la cote de certains capteurs et/ou laisses de crue qui ne correspondent pas à la hauteur de l'eau mais à cette grandeur.

NB : Demande du SPC Meuse Moselle (Jean-Pierre WAGNER)

**Comment by ccoulet** [comment]
Demande transférée vers le code Mascaret.
